# Generated by Django 5.2.1 on 2025-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0003_skillcategory_remove_studentprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='mobile_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jit.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
