# Generated by Django 5.2.1 on 2025-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jit', '0005_studentprofile_achievements_studentprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
